[book]
title = "لغة البرمجة Rust"
author = "Steve Klabnik، Carol Nichols ترجمة:عمرو سليمان"
language = "ar"
text-direction = "rtl" 

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css", "theme/arabic.css"]
additional-js = ["ferris.js"]